In this notebook we investigate which numerical features seem to be correlated. 

We will be computing the pearson correlation, which ranges from -1 to 1. 0 means no relationship; the closer to 1 the stronger the positive relationship.

In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv(r"C:\Users\arubi\Desktop\datascience2025\erdos-uncreatives\Data Cleaning and Visualization\cleaner_transformed_data_Rachael2.csv")
df.columns

Index(['Unnamed: 0', 'channelDescription', 'channelJoinedDate',
       'channelTotalVideos', 'channelTotalViews', 'channelUsername',
       'commentsCount', 'date', 'duration', 'id', 'isChannelVerified', 'likes',
       'numberOfSubscribers', 'order', 'text', 'title', 'url', 'viewCount',
       'likes per subscriber', 'comments per subscriber',
       'views per subscriber', 'duration in seconds', 'datetime date'],
      dtype='object')

Our numerical features include:

Duration in seconds
Likes/subscriber
comments/subscriber
views/subscriber

In [73]:
print(np.corrcoef(x = df["duration in seconds"], y = df["views per subscriber"]))
print(np.corrcoef(x = df["duration in seconds"], y = df["likes per subscriber"]))
print(np.corrcoef(x = df["duration in seconds"], y = df["comments per subscriber"]))

[[ 1.         -0.03303727]
 [-0.03303727  1.        ]]
[[ 1.         -0.01842462]
 [-0.01842462  1.        ]]
[[ 1.         -0.04685202]
 [-0.04685202  1.        ]]


In [ ]:
#Conclusion: Longer videos do worse, on all counts. They are most 
#Also longer videos do worse, but not by a huge amount.

In [75]:
print(np.corrcoef(x = df["views per subscriber"], y = df["likes per subscriber"]))
print(np.corrcoef(x = df["views per subscriber"], y = df["comments per subscriber"]))

[[1.        0.9444172]
 [0.9444172 1.       ]]
[[1.         0.51852064]
 [0.51852064 1.        ]]


In [77]:
#Conclusion: If your video gets seen, people are really likely to also like and comment. They are much more likely to like your video rather than comment.

In [79]:
print(np.corrcoef(x = df["likes per subscriber"], y = df["comments per subscriber"]))

[[1.         0.51630558]
 [0.51630558 1.        ]]


In [ ]:
#Conclusion: Likes are not as highly correlation to comments. These are measuring different but related things.