In this notebook, we will create and compare several models. Our target feature for this notebooks is (Likes+Comments/(Views+1))
which we will call "engagement". We have added 1 to the denonimator just to ensure we never divide by zero. 

Please note that we are not really creating a "model" of our data. That is, we do not believe our data is fully explained by our features or any features that can be extracted from our data set. This explains the poor fit. 

In [37]:
import pandas as pd
import numpy as np

df = pd.read_csv('../data/new/no_early_dates_all_features_train.csv')
features = ["popular_brand", "has_any_affiliate", "product", "budget", "self_ref", "korean", "speed", 
            "skills/teach", "comparing_products", "prime_hour", "hashtag_indicator", "hasAdinTitle", "hasAdinText"]

#Create the target column $y$ here 

df["y"] = (df["likes"] + df["commentsCount"])  / (df["viewCount"] + 1) 

#get rid of noisy columns
df = df[ features + ["y"] ] 

In [38]:
#import everything

from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import Pipeline 
from sklearn.linear_model import LinearRegression
from sklearn.metrics import root_mean_squared_error, r2_score
from sklearn.model_selection import train_test_split


In [39]:
#Do an 80-20 Train Test Split Here. Never ever touch the testing set please!

df_train, df_test = train_test_split(df, shuffle = True, test_size = .2, random_state = 42) #We can't stratify because we have too many categorical features. I hope this is ok
#DO NOT TOUCH THE ABOVE X_TEST VARIABLE FOR ANY REASON

#We want a very basic idea of the MSE and other metrics for each model, before we do proper cross-validation. We use a secondary split for this.
df_tt, df_ho = train_test_split(df_train, shuffle = True, test_size = .2, random_state = 42)


In [40]:
#Create the baseline model here

class BaseMeanModel():
    def __init__(self):
        self.mean_value = None
    
    def fit(self, values : pd.Series):
        self.mean_value = values.mean()

    def predict(self, inputs=None):
        if inputs is None:
            return self.mean_value
        return len(inputs) * [self.mean_value]
    
    
model = BaseMeanModel()
model.fit(df_tt["y"])

# R2 is negative because training set and the hold out set have different average values
y_pred = model.predict(df_ho[features])
rmse = root_mean_squared_error(df_ho["y"], y_pred)
r2 = r2_score(df_ho["y"], y_pred)
print(f"Root Mean Squared Error: {rmse:.6f}")
print(f"R-squared: {r2:.4f}")

Root Mean Squared Error: 0.029123
R-squared: -0.0056


In [41]:
#Creat the basic linear regression model here 
###Fitting the basic linear regression model using the training set and print the summary of the model.
model = LinearRegression()
model.fit(df_tt[features], df_tt["y"])
# Evaluate the model
y_pred = model.predict(df_ho[features])
rmse = root_mean_squared_error(df_ho["y"], y_pred)
r2 = r2_score(df_ho["y"], y_pred)
print(f"Root Mean Squared Error: {rmse:.6f}")
print(f"R-squared: {r2:.4f}")

Root Mean Squared Error: 0.028268
R-squared: 0.0526


In [42]:
#Create the basic linear regression model here with lasso regression. 


from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LassoCV, Lasso
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error, explained_variance_score
from sklearn.model_selection import cross_val_score


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(df_tt[features] )
X_test_scaled = scaler.transform( df_ho[features])

alpha = 0.0001
lasso = Lasso(alpha=alpha, random_state=42, max_iter=10000)

#cv_scores = cross_val_score(lasso, X_train_scaled, df_tt["y"], cv=5,scoring='neg_mean_squared_error')
#cv_rmse = np.sqrt(-cv_scores.mean())

lasso.fit(X_train_scaled, df_tt["y"])

y_pred = lasso.predict(X_test_scaled)

# Calculate metrics
mse = mean_squared_error(df_ho["y"], y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(df_ho["y"], y_pred)
r2 = r2_score(df_ho["y"], y_pred)
exp_var = explained_variance_score(df_ho["y"], y_pred)


print(f"\nAlpha: {alpha}")
print(f"Test MSE: {mse:.6f}, RMSE: {rmse:.6f}, MAE: {mae:.6f}")
print(f"R² Score: {r2:.6f}, Explained Variance: {exp_var:.6f}")
#print(f"Cross-validated RMSE: {cv_rmse:.6f}")



Alpha: 0.0001
Test MSE: 0.000801, RMSE: 0.028294, MAE: 0.021494
R² Score: 0.050788, Explained Variance: 0.055645


In [43]:
#Create a model whose features include all interaction terms
pipe = Pipeline([  ("interaction terms", PolynomialFeatures(degree = 2, interaction_only = True, include_bias = False) ),
                   ("linear model", LinearRegression())
]) 
#setting degree = 2 creates all pairwise interaction terms. 

pipe.fit( df_tt[features], df_tt["y"]) 
pred = pipe.predict( df_ho[features] )

mse = mean_squared_error(df_ho["y"], pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(df_ho["y"], pred)
r2 = r2_score(df_ho["y"], pred)
exp_var = explained_variance_score(df_ho["y"], pred)


print(f"Test MSE: {mse:.6f}, RMSE: {rmse:.6f}, MAE: {mae:.6f}")
print(f"R² Score: {r2:.6f}, Explained Variance: {exp_var:.6f}")

Test MSE: 0.000789, RMSE: 0.028086, MAE: 0.021365
R² Score: 0.064693, Explained Variance: 0.069416


In [44]:
#Create a model with all interaction terms and lasso regression 

#Create a model with all interaction terms and lasso regression 
from sklearn.linear_model import Lasso, LassoCV
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_df_tt = scaler.fit_transform( df_tt[features] )
scaled_df_ho = scaler.transform( df_ho[features] )

# using lasso cv to find the best alpha
# lasso = LassoCV(cv=5, random_state=42, max_iter=10000, alphas=np.logspace(-4, 1, 30))
# lasso.fit(df_tt[features], df_tt["y"])
# pred = lasso.predict(df_ho[features])
# print("Lasso CV MSE:", root_mean_squared_error(df_ho["y"], pred))
# print("Optimal alpha:", lasso.alpha_)

pipe = Pipeline([
    ("interaction terms", PolynomialFeatures(degree=2, interaction_only=True, include_bias=False)),
    ("lasso", Lasso(alpha=0.0001, max_iter=10000))
])
pipe.fit(scaled_df_tt, df_tt["y"])
pred = pipe.predict(scaled_df_ho)
print("MSE : ", root_mean_squared_error(df_ho["y"], pred))

# Get lasso coefficients
lasso_coeffs = pd.Series(pipe.named_steps['lasso'].coef_, index=pipe.named_steps['interaction terms'].get_feature_names_out(features))
lasso_coeffs = lasso_coeffs[lasso_coeffs != 0]
# print(lasso_coeffs)

MSE :  0.028043613259332946


In [45]:
#Do cross-validation to compare all models 

#Model 0: Baseline Average
#Model 1: Basic Linear Regression Model
#Model 2: Linear Regression with Lasso
#Model 3: Linear Regression with interaction terms
#Model 4: Linear Regression with interactions and lasso

from sklearn.model_selection import KFold
num_splits = 5
num_models = 5

kfold = KFold(num_splits,
              random_state = 42,
              shuffle=True)

rmses = np.zeros((num_models, num_splits))

for i, (train_index, test_index) in enumerate(kfold.split(df_train)): 

    df_tt = df_train.iloc[train_index]
    df_ho = df_train.iloc[test_index] 

    #Model 0: Baseline Average
    model = BaseMeanModel()
    model.fit(df_tt["y"])
    y_pred = model.predict(df_ho[features])
    rmses[0,i] = root_mean_squared_error(df_ho["y"], y_pred)

    #Model 1: Basic Linear Regression Model
    model = LinearRegression()
    model.fit(df_tt[features], df_tt["y"])
    y_pred = model.predict(df_ho[features])
    rmses[1,i] = root_mean_squared_error(df_ho["y"], y_pred)

    #Model 2: Linear Regression with Lasso
    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(df_tt[features] )
    X_test_scaled = scaler.transform( df_ho[features])
    alpha = 0.0001
    lasso = Lasso(alpha=alpha, random_state=42, max_iter=10000)
    lasso.fit(X_train_scaled, df_tt["y"])
    y_pred = lasso.predict(X_test_scaled)
    rmses[2,i] = root_mean_squared_error(df_ho["y"], y_pred)

    #Model 3: Linear Regression with interaction terms
    pipe = Pipeline([  ("interaction terms", PolynomialFeatures(degree = 2, interaction_only = True, include_bias = False) ),
                   ("linear model", LinearRegression())
                    ]) 
    pipe.fit( df_tt[features], df_tt["y"]) 
    y_pred = pipe.predict( df_ho[features] )
    rmses[3,i] = root_mean_squared_error(df_ho["y"], y_pred)

    #Model 4: Linear Regression with interactions and lasso
    scaler = StandardScaler()
    scaled_df_tt = scaler.fit_transform( df_tt[features] )
    scaled_df_ho = scaler.transform( df_ho[features] )
    pipe = Pipeline([
    ("interaction terms", PolynomialFeatures(degree=2, interaction_only=True, include_bias=False)),
    ("lasso", Lasso(alpha=0.0001, max_iter=10000))
                    ])
    pipe.fit(scaled_df_tt, df_tt["y"])
    y_pred = pipe.predict(scaled_df_ho)
    rmses[4,i] = root_mean_squared_error(df_ho["y"], y_pred)


print(rmses)

[[0.02912292 0.03097684 0.03660978 0.03208654 0.03187867]
 [0.02826778 0.03054189 0.03612537 0.03144913 0.03141039]
 [0.02829447 0.03053    0.03612154 0.03145887 0.03140658]
 [0.02808646 0.02990547 0.03575154 0.03147655 0.03093863]
 [0.02804361 0.02988082 0.03573833 0.03136356 0.03087301]]


In [46]:
rmses.mean(axis = 1)
#Pretty much as expected, models with the most features (i.e., models that included interaction terms) did the best.
#Interestingly, Lasso regression slightly outperformed regular linear regression. 

array([0.03213495, 0.03155891, 0.03156229, 0.03123173, 0.03117987])

In [47]:
#Note that in the RMSE matrix, each ROW is a different model and each COLUMN is a CV. 
#In the above we took an average of each ROW. 
#As a sanity check we look at the full RMSE matrix and see that yes, in each column the first row is the largest number,
#the second row is (often) the second largest number, etc. This means there is a consistent pattern as to the performance of our models
#and it is not just random noise. 

---Final Interpretation---

Almost as expected, the model with the most features (i.e., the model that includes all interaction terms) performed the best. This could just be because every time a linear model has more features it will perform better, in the sense that it will have a lower rmse. 

Interestingly, our lasso model slightly outperformed our non-lasso model. 

We want to take the coefficients of our highest performing model and compare them. This is where our analysis was really headed.
Mathematically, the features with the highest coefficients are those that contribute the most to the trend line.



In [49]:
#A final fitting to the whole training data set 
scaler = StandardScaler()
scaled_df = scaler.fit_transform( df[features] )
pipe = Pipeline([
    ("interaction terms", PolynomialFeatures(degree=2, interaction_only=True, include_bias=False)),
    ("lasso", Lasso(alpha=0.0001, max_iter=10000))
                    ])
pipe.fit(scaled_df, df["y"])

lasso_coeffs = pd.Series(pipe.named_steps['lasso'].coef_, index=pipe.named_steps['interaction terms'].get_feature_names_out(features))
sig_lasso_coeffs = lasso_coeffs[lasso_coeffs != 0]
print(sig_lasso_coeffs)

popular_brand                    -0.002639
has_any_affiliate                 0.001629
product                          -0.001590
budget                           -0.000186
self_ref                          0.002271
                                    ...   
prime_hour hasAdinTitle          -0.000164
prime_hour hasAdinText            0.000089
hashtag_indicator hasAdinTitle   -0.000815
hashtag_indicator hasAdinText    -0.001132
hasAdinTitle hasAdinText          0.000106
Length: 73, dtype: float64


In [50]:
new = sig_lasso_coeffs.sort_values(key=abs)

In [51]:
new.tail(10)

product                          -0.001590
has_any_affiliate                 0.001629
popular_brand skills/teach        0.001649
skills/teach hashtag_indicator   -0.001696
self_ref speed                   -0.001802
prime_hour                        0.001925
self_ref                          0.002271
product hashtag_indicator         0.002460
popular_brand                    -0.002639
hashtag_indicator                -0.003277
dtype: float64